### ISSUE TITLE
Add click event for table rows to highlight + add selection data to userData

### ISSUE THREAD

**Issue by esharri2** [TheCoolKidsUNC/DateNightApp#39]
Click should highlight the row (and unhighlight other rows if they had been clicked) and added all the data about the movie or restaurant to the userData.dinnerDecision or userData.movieDecision.

**Comment by abreaw** [comment]
table rows click event coded now ... showing some information in the final choice details views but still needs further work once we get the api info sorted and agreed on ... resolved with merge #52
