### ISSUE TITLE
check why restaurant API call is not returning same results for everyone

### ISSUE THREAD

**Issue by abreaw** [TheCoolKidsUNC/DateNightApp#45]
table is loading in UI now but we don't have the data we expected from the API call ... need to look and see what else we can use or what we would like to do in it's place

**Comment by esharri2** [comment]
@abreaw I discovered a bug last night that may have been causing this? The `randomizeArray` function was actually modifying the array passed to it. So, for example, the part you wrote to pull 10 random items for the dropdowns was removing 10 items from the validationData array. Sorry! Anyway, I fixed it I think, with help from this post: https://stackoverflow.com/questions/14491405/javascript-passing-arrays-to-functions-by-value-leaving-original-array-unaltere

Are you still getting the sense that it's not returning the right results, or should we close this issue?

**Comment by esharri2** [comment]
I think I'm mostly getting 1 result now .... looks like the API is returning more though.

**Comment by esharri2** [comment]
Here is a consistent experience I'm getting...the `userData.movieOptions` has 3 options (sometimes less if it's a less common type of restaurant), only `userData.movieOptions[0]` prints to the table. When you click it, `userData.movieOptions[2]` goes into the final choice section.
