### ISSUE TITLE
dropdown list needs to be properly capitalized

### ISSUE THREAD

**Issue by abreaw** [TheCoolKidsUNC/DateNightApp#49]
currently the on page load function is grabbing the data from the validation array object and it is just loading 10 random items into the list for the user to select ... the list doesn't have proper capitalization displaying

**Comment by esharri2** [comment]
whoever takes this -- easiest option might be css...

```
selector {
    text-transform: capitalize;
}
```

**Comment by abreaw** [comment]
Didn't know that existed :) ... Thanks for the tip!
