### ISSUE TITLE
Show some kind of "no results" message if APIs do not find restaurant / movie

### ISSUE THREAD

**Issue by esharri2** [TheCoolKidsUNC/DateNightApp#85]
This could pop as the yellow error message that we're using for validation issues, or it could show up in the area where the table is. Not sure which is best -- leaning toward yellow error message above the form.

**Comment by abreaw** [comment]
There is another area for errors added above the table views for the choices ... i will add it there and if we need to move to the user form area then we can do that later

**Comment by abreaw** [comment]
pr #89 fixes this issue
